### ISSUE TITLE
[BUG] Preference bundle is invalid

### ISSUE THREAD

**Issue by TheAwesome98-Real** [liberatoaguilar/DontSwipe#1]

**Comment by jalsco** [comment]
I have just discovered same problem. 

I am very familiar with DontSwipe. It is one of my favorite tweaks !  Thank you for making it ✅🙏🏻 I used DontSwipe without any problem for a couple years on my 11ProMax running iOS 14 (jb by unc0ver ).  Early in 2024 I upgraded to 12 ProMax running iOS 15.4 (jb by Dopamine) and I really WISH Don'tSwipe is available for that, but sadly it is not 😥 

The current problem -  to keep kids occupied on long travel I setup a bunch of videos on a iPad Mini2 (A7 processor, iOS 12.5.7, jb by Chimera ).  I need to stop the kids touching the screen and changing whats running - so I installed DontSwipe 1.2-3 - from Sileo. It says supports ios 11.1.2 - 13.6. The installation was successful with no errors or messages. Activator is correctly installed and shows in Settings, as it should... 

The problem is - even after a few resprings and a few re-installs the DontSwipe app does show in Settings BUT only with a message "There was an error loading the Preferences Bundle for DontSwipe".    

I really hoping ( begging and praying 🙏🏻 ) there is an quick fix, or patch possible - or some other way to fix this...  and can be done in the coming days (before my long travel). To start,  I just hope you are still monitoring this 😊.  

As I wrote - DontSwipe is a super useful tweak, and I thank you for all the use I already got from it on my other device.

just hoping you can help with this problem 

![image](https://github.com/user-attachments/assets/07fbb90f-9d03-4be6-a341-c89aab787a15)

**Comment by liberatoaguilar** [comment]
Check #2 for a potential workaround.
